# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# + -------------------------------------------------------------------------------- + #
# ! 사용하지 않고 싶은 메시지는 메시지 앞에 '#'을 달아주시면 됩니다.
# ! 예시) 접두사를 사용고 싶지 않은 경우
# ! # prefix: ' &fItem&6DB &6| '
# + -------------------------------------------------------------------------------- + #
messages:
  itemdb:
    # (메시지 앞에 붙는) 접두사
    prefix: ' &fItem&6DB &6| '

    # 콘피그 파일을 리로드하였을 때 출력되는 메시지
    reloadComplete: '&f콘피그 파일을 리로드하였습니다.'

    # 아이템을 아이템저장소(ItemDB)에 저장했을 때 출력되는 메시지
    # 저장된 아이템 ID : {id}
    # 아이템 이름: {displayName}
    # 아이템 종류: {material}
    saveItemDB: '&f손에 든 아이템을 아이템저장소(Item&6DB)&f에 &b{id}&f이름으로 저장하였습니다.'

    # 아이템저장소(ItemDB)에 있는 아이템을 삭제했을 때 출력되는 메시지
    # 저장된 아이템 ID : {id}
    deleteItemDB: '&f아이템저장소(Item&6DB)&f에 &b{id}&f의 아이템을 삭제하였습니다.'

    # 아이템을 지급하였을 때 출력되는 메시지
    # 지급받은 플레이어 : {target}
    # 지급한 플레이어 : {player}
    # 지급한 아이템 ID : {id}
    giveItemDB: '&6{target}&f님에게 &b{id}&f의 아이템을 지급하였습니다.'
    # giveItemDBTarget: "&6{player}&f님에게 &b{id}&f의 아이템을 지급받았습니다."

    # 아이템을 모든 플레이어에게 지급하였을 때 출력되는 메시지
    # 지급한 플레이어 : {player}
    # 지급한 아이템 ID : {id}
    # 지급 받은 플레이어의 수 : {count}
    giveAllItemDB: ' &fItem&6DB &6| {player}&f님께서 모든 플레이어에게 &b{id}&f의 아이템을 지급하였습니다.'

    # 아이템을 받았을 때 출력되는 메시지
    # 받은 아이템 ID : {id}
    getItemDB: '&b{id}&f의 아이템을 받았습니다.'

errorMessages:
  itemdb:
    # 펄미션(권한)이 없을 때 출력되는 메시지
    noPermission: '&c당신은 해당 명령어를 사용할 권한이 없습니다.'

    # 잘못된 명령어를 입력하였을 때 출력되는 메시지
    wrongCommand: '&c잘못된 명령어입니다. 명령어를 확인해주세요.'

    # 콘솔에서 사용 불가능한 명령어를 입력하였을 때 출력되는 메시지
    noConsoleCommand: '&c콘솔에서 사용 불가능한 명령어입니다.'

    # 플레이어 닉네임을 입력하지 않을 때 출력되는 메시지
    noPlayerName: '&c플레이어 닉네임을 입력해주세요.'

    # 플레이어가 오프라인이거나 찾을 수 없을때 출력되는 메시지
    # {player} : 플레이어 닉네임
    notFoundPlayer: '&c플레이어를 찾을 수 없습니다.'

    # 아이템 이름을 입력하지 않았을 때 출력되는 메시지
    noItemId: '&c아이템 이름(ID)를 입력해주세요.'

    # 존재하지 않은 아이템이름(ID)를 입력하였을 때 출력되는 메시지
    noFoundId: '&c존재하지 않은 아이템 이름(ID)입니다.'

    # 손에 아이템을 들지 않았을 때 출력되는 메시지
    noItemInHand: '&c손에 아이템을 들어주세요.'