# + ---------------------------------------------------------------- + #
# | MESSAGE SETTINGS
# + ---------------------------------------------------------------- + #
# | 전송하고 싶지 않은 메시지는 앞에 '#'을 달면 출력되지 않습니다.
# | 예시)
# |
# |

messages:

errorMessages: