# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# + -------------------------------------------------------------------------------- + #
# ! 사용하지 않고 싶은 메시지는 메시지 앞에 '#'을 달아주시면 됩니다.
# ! 예시) 접두사를 사용고 싶지 않은 경우
# ! # prefix: '[ ItemDB ]'
# + -------------------------------------------------------------------------------- + #
messages:
  itemdb:
    # (메시지 앞에 붙는) 접두사
    prefix: '[ ItemDB ]'

    # 콘피그 파일을 리로드하였을 때 출력되는 메시지
    reloadComplete: "&f콘피그 파일을 리로드하였습니다."

errorMessages:
  itemdb:
    # 펄미션(권한)이 없을 때 출력되는 메시지
    noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

    # 잘못된 명령어를 입력하였을 때 출력되는 메시지
    wrongCommand: "&c잘못된 명령어입니다. 명령어를 다시 확인해주세요."

    # 플레이어 닉네임을 입력하지 않을 때 출력되는 메시지
    noPlayerName: "&c플레이어 닉네임을 입력해주세요."

